"use strict";
/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const fs_1 = require("fs");
const path_1 = require("path");
const json5_1 = tslib_1.__importDefault(require("json5"));
const dedent_1 = tslib_1.__importDefault(require("dedent"));
const dev_utils_1 = require("@kbn/dev-utils");
const constants_1 = require("../constants");
const config_1 = require("./config");
dev_utils_1.run(async () => {
    const genInfo = dedent_1.default `
      /**
       * PLEASE DO NOT MODIFY
       *
       * This file is automatically generated by running \`node scripts/build_renovate_config\`
       *
       */
    `;
    fs_1.writeFileSync(path_1.resolve(constants_1.REPO_ROOT, 'renovate.json5'), `${genInfo}\n${json5_1.default.stringify(config_1.RENOVATE_CONFIG, null, 2)}\n`);
}, {
    description: 'Regenerate the renovate.json5 file at the root of the repo based on the config in src/dev/renovate',
});
